### ISSUE TITLE
Build the Zipcode form React component

### ISSUE THREAD

**Issue by shidhincr** [shidhincr/LookAround_React#2]

**Comment by ivinjose** [comment]
@shidhincr Have committed this issue in zipcode branch. Take a look at it. 

Note: Will add unit testing to it in next commit; need to read about it first.

**Comment by shidhincr** [comment]
Is it okay to merge ? can you open the pull request ? so that I can review and merge it

**Comment by ivinjose** [comment]
PR created. Check.

**Comment by shidhincr** [comment]
Issue is fixed in PR
